#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "movies.h"

#define MAX_USERS 30
#define MAX_NAME_LENGTH 50
#define MAX_MOVIE_LENGTH 150
#define MAX_RATING_LENGTH 90

FILE *fptr;
char **userDb, **moviesDb;
float movieRating, **ratingsDb;
int usersCount = 0, moviesCount = 0, movieIdx;
bool moviesRead = false, ratingsRead = false;

/**
 * this function prints the main menu options to the console.
 * @return none.
 */
void displayMenu() {
    printf("-----------------------------\n");
    printf("          Main Menu            \n");
    printf("-----------------------------\n");
    printf(" 1. Register User\n");
    printf(" 2. Display Movies\n");
    printf(" 3. Rate a Movie\n");
    printf(" 4. Get Movie Recommendations\n");
    printf(" 0. Exit\n");
    printf("-----------------------------\n");
    printf("Enter your choice: ");
}

/**
 * this function registers a new user into `userDb`.
 * 
 * it checks if the user is already registered, and if not, adds it to `userDb`, and writes to `userData.txt`.
 * @return none.
 */
void registerUser() {
    char newUser[MAX_NAME_LENGTH];
    bool userFound;

    readUsersFromDb();
    do {
        printf("\nEnter username to register: ");
        scanf("%30s", newUser);

        userFound = isUserRegistered(newUser);
        if(userFound) {
            printf("~~ User already exists. Please choose a different name.\n");
            continue;
        }
        
        //add new user to the database, remove the newline at the end of the string, and update the number of users
        strcpy(userDb[usersCount], newUser);
        userDb[usersCount][strcspn(userDb[usersCount], "\n")] = '\0';
        usersCount++;
        printf("~~ User %s has been successfully registered.\n", newUser);
    } while(userFound);
    writeUsersToDb();
}

/**
 * this function displays all available movies to the console. 
 * @return none.
 */
void displayMovies() {
    readMovies();

    //if the file was opened and read successfully
    if(moviesRead) {
        printf("\n-----------------------------\n");
        printf("        Movie Database         \n");
        printf("-----------------------------\n");

        for(int i = 0; i < moviesCount; i++) {
            if(i != (moviesCount - 1)) {
                printf("%d. %s\n", (i + 1), moviesDb[i]);
                continue;
            }
            printf("%d. %s", (i + 1), moviesDb[i]);
        }
        printf("\n----------\n");
    }
}

/**
 * this function allows a user to rate a movie. it prompts the user to enter their username, then displays a list of all available movies to rate.

 * after the user selects a movie and provides a rating, the rating is recorded and written to `ratingsData.txt`.
 * 
 * if the user is not found or if the movie number or rating provided is invalid, appropriate messages are displayed.
 * @return none.
 */
void rateMovie() {
    char validateUser[MAX_NAME_LENGTH];
    readUsersFromDb();

    printf("\nEnter your username: ");
    scanf("%30s", validateUser);

    bool userFound = isUserRegistered(validateUser);
    if(!userFound) {
        printf("~~ User not found. Please register first.\n");
        return;
    }

    displayMovies();
    int userIndex = findUserIndex(validateUser);

    //prompt the user to enter the movie number and rating
    movieIdx = validateInput("\nEnter the number of the movie you want to rate: ", moviesCount);
    movieRating = validateInput("Enter your rating (1-5): ", 5);

    readRatingsFromDb();
    //update the movie rating
    ratingsDb[userIndex][movieIdx - 1] = movieRating;

    writeRatingsToDb();
    printf("\n~~ Rating recorded successfully.\n");
}

/**
 * this function recommends movies for a user based on the ratings of other users. 
 * 
 * it prompts the user to enter their username, then checks if the user is registered.
 * 
 * if the user is found, their recommendations are generated by calculating the average rating of unseen movies based on ratings from other users.
 * @return none.
 */
void recommendMovies() {
    char validateUser[MAX_NAME_LENGTH], *nameAndGenre, recommendation[MAX_MOVIE_LENGTH];
    int countedRatings = 0, movieCounter = 1;
    float sumRatings = 0;

    readUsersFromDb();
    printf("\nEnter your username: ");
    scanf("%14s", validateUser);

    bool found = isUserRegistered(validateUser);
    if(!found) {
        printf("~~ User not found. Please register first.\n");
        return;
    }

    int userIndex = findUserIndex(validateUser);
    readMovies();
    readRatingsFromDb();

    printf("\n-----------------------------\n");
    printf("      Recommended Movies       \n");
    printf("-----------------------------\n");

    for(int i = 0; i < moviesCount; i++) { //for each movie
        for(int j = 0; j < usersCount; j++) { //for each user

            //if the user hasn't seen the movie(movie rating is 0.0 by default)
            if(ratingsDb[userIndex][i] == 0.0) {
                if(ratingsDb[j][i] != 0.0) { //if the other users have seen the movie(movie rating is not 0.0)
                   sumRatings += ratingsDb[j][i]; //update the total rating of the other users
                   countedRatings++; //count the number of users that have seen the movie
                }
            }
        }

        if(countedRatings != 0) {
            nameAndGenre = strtok(moviesDb[i], "-"); //split the string by the hyphen
            float predictedRating = sumRatings / countedRatings; //calculate the average rating of other users

            //format the components into the desired string
            sprintf(recommendation, "%d. %s-- Predicted Rating: %.1f\n", movieCounter, nameAndGenre, predictedRating);
            printf("%s", recommendation);
            movieCounter++;
        }
        sumRatings = 0;
        countedRatings = 0;
    }
}



// ~~~~~~~~~~~~~~~ helper functions ~~~~~~~~~~~~~~~ //
/**
 * this function reads the users from the `userData.txt` file, and populates the `userDb` array.
 * 
 * if the file does not exist, it prints an error message and returns.
 * @return none.
 */
void readUsersFromDb() {
    fptr = fopen("textfiles/userData.txt", "r");
    char nameAndNumber[MAX_NAME_LENGTH];

    if(fptr == NULL) { //the file does not exist
        printf("File \'userData.txt\' was not found.\n\n");
        return;
    }

    //free previously allocated memory for userDb
    if(usersCount != 0) {
        freeCharMemory(userDb, MAX_USERS);
    }

    //dynamically allocate memory for userDb
    userDb = (char **)malloc(MAX_USERS * sizeof(char *));
    for(int i = 0; i < MAX_USERS; i++) {
        userDb[i] = (char *)malloc(MAX_NAME_LENGTH * sizeof(char));
    }

    usersCount = 0;
    while(fgets(nameAndNumber, sizeof(nameAndNumber), fptr)) {
        //split the string to record only the name and not the number
        char *nameOnly = strtok(nameAndNumber, " ");

        //read users into the database, remove the newline at the end of the string, and update the number of users
        strcpy(userDb[usersCount], nameOnly);
        userDb[usersCount][strcspn(userDb[usersCount], "\n")] = '\0';
        usersCount++;
    }
    fclose(fptr);
}

/**
 * this function writes the users from the `userDb` array to the `userData.txt` file.
 * 
 * if the file does not exist, it creates a new one.
 * @return none.
 */
void writeUsersToDb() {
    fptr = fopen("textfiles/userData.txt", "wt");
    for(int i = 0; i < usersCount; i++) {
        //if not the last user, add newline after writing to file and continue
        if(i != (usersCount - 1)) {
            fprintf(fptr, "%s %d\n", userDb[i], (i + 1));
            continue;
        }
        fprintf(fptr, "%s %d", userDb[i], (i + 1));
    }
    fclose(fptr);
}

/**
 * this function checks if a user is registered in `userDb`.
 * 
 * @param username the sought username.
 * @return true if the user is registered, otherwise false.
 */
bool isUserRegistered(const char *username) {
    for(int i = 0; i < usersCount; i++) {
        //making the search case-insensitive
        if(strcasecmp(username, userDb[i]) == 0) return true;
    }
    return false;
}

/**
 * this function reads the movies from the `moviesData.txt` file, and populates the `moviesDb` array.
 * 
 * if the file does not exist, it prints an error message and returns.
 * @return none.
 */
void readMovies() {
    fptr = fopen("textfiles/moviesData.txt", "r");
    char display[MAX_MOVIE_LENGTH];

    if(fptr == NULL) { //the file does not exist
        printf("File \'moviesData.txt\' was not found.\n\n");
        return;
    }

    //free previously allocated memory for moviesDb
    if(moviesCount != 0) {
        freeCharMemory(moviesDb, 10);
    }

    //dynamically allocate memory for moviesDb
    moviesDb = (char**)malloc(10 * sizeof(char*));
    for(int i = 0; i < 10; i++) {
        moviesDb[i] = (char *)malloc(MAX_MOVIE_LENGTH * sizeof(char));
    }

    moviesCount = 0;
    while(fgets(display, sizeof(display), fptr)) {
        //split the string by the space
        char *title = strtok(display, " ");
        char *genre = strtok(NULL, " ");
        char *rating = strtok(NULL, " ");

        //replace underscores in the title with spaces
        for(int i = 0; title[i] != '\0'; i++) {
            if(title[i] == '_') {
                title[i] = ' ';
            }
        }

        //format the components into the desired string
        char formattedString[MAX_MOVIE_LENGTH];
        sprintf(formattedString, "%s (%s) - %s", title, genre, rating);

        //add formatted string to movie database, remove the newline at the end of the string, and update the number of movies
        strcpy(moviesDb[moviesCount], formattedString);
        moviesDb[moviesCount][strcspn(moviesDb[moviesCount], "\n")] = '\0';
        moviesCount++;
    }
    moviesRead = true;

    fclose(fptr);
}

/**
 * this function reads the ratings from the `ratingsData.txt` file, and populates the `ratingsDb` array.
 * 
 * if the file does not exist, it prints an error message and returns.
 * @return none.
 */
void readRatingsFromDb() {
    fptr = fopen("textfiles/ratingsData.txt", "r");

    char ratings[MAX_RATING_LENGTH], *token;
    int userIndex = 0, movieIndex = 0;

    if(fptr == NULL) { //the file does not exist
        printf("File \'ratingsData.txt\' was not found.\n\n");
        return;
    }

    //free previously allocated memory for ratingsDb
    if(ratingsRead) {
        freeFloatMemory(ratingsDb, usersCount);
    }

    //dynamically allocate memory for ratingsDb
    ratingsDb = (float **)malloc(usersCount * sizeof(float *));
    for(int i = 0; i < MAX_USERS; i++) {
        ratingsDb[i] = (float *)malloc(moviesCount * sizeof(float));
    }

    fgets(ratings, sizeof(ratings), fptr); //skip the first line
    while(fgets(ratings, sizeof(ratings), fptr) != NULL) {
        token = strtok(ratings, " ");

        while(token != NULL) { //keep splitting by the space till the end of the string
            ratingsDb[userIndex][movieIndex] = atof(token);
            movieIndex++;
            token = strtok(NULL, " ");
        }
        movieIndex = 0;
        userIndex++;
    }
    ratingsRead = true;

    fclose(fptr);

    //new users may have been registered, so set their ratings to the default(0.0)
    for(int i = userIndex; i < usersCount; i++) {
        for(int j = 0; j < moviesCount; j++) {
            ratingsDb[i][j] = 0.0;
        }
    }
}

/**
 * this function writes the ratings from the `ratingsDb` array to the `ratingsData.txt` file.
 * 
 * if the file does not exist, it creates a new one.
 * @return none.
 */
void writeRatingsToDb() {
    fptr = fopen("textfiles/ratingsData.txt", "wt");

    fprintf(fptr, "%d %d\n", usersCount, moviesCount);
    for(int i = 0; i < usersCount; i++) {
        for(int j = 0; j < moviesCount; j++) {
            if(j != moviesCount - 1) { //if not the last movie rating of a user, add spacing after writing the movie rating to file and continue
                fprintf(fptr, "%.1f ", ratingsDb[i][j]);
                continue;
            }
            if(i != usersCount - 1) { //if not the last user, add newline after writing the last rating of all movies to file and continue
                fprintf(fptr, "%.1f\n", ratingsDb[i][j]);
                continue;
            }
            fprintf(fptr, "%.1f", ratingsDb[i][j]); //if at the last movie and user, neither add newline nor spacing
        }
    }
    fclose(fptr);
}

/**
 * this function validates a user-entered movie number & rating to ensure it falls within the specified range.
 * 
 * @param string the prompt instruction to display.
 * @param maxRating the upper bound digit allowed.
 * @return the validated input.
 */
float validateInput(const char *string, int maxRating) {
    float exactRating;

    do {
        printf("%s", string); //print the prompt instruction
        scanf("%f", &exactRating);

        if(exactRating < 1 || exactRating > maxRating) {
            printf("Invalid rating. Please enter a rating between 1 and %d.\n", maxRating);
        }
    } while(exactRating < 1 || exactRating > maxRating);

    return exactRating;
}

/**
 * this function finds the index of a user in the userDb array based on the username.
 * 
 * @param username the sought username.
 * @return the index of the user if found, otherwise -1.
 */
int findUserIndex(const char *username) {
    for(int i = 0; i < usersCount; i++) {
        if(strcasecmp(username, userDb[i]) == 0) { //making the search case-insensitive
            return i;
        }
    }
    return -1;
}

/**
 * this function deallocates memory that was dynamically allocated for an array of strings.
 * 
 * @param database pointer to strings array to be deallocated.
 * @param arrayLength array length.
 * @return none.
 */
void freeCharMemory(char **database, int arrayLength) {
    //iterate through each string in the array and free its memory
    for(int i = 0; i < arrayLength; i++) {
        free(database[i]);
    }

    //free the memory allocated for the array itself
    free(database);
}

/**
 * this function deallocates memory that was dynamically allocated for a 2D array of floats.
 * 
 * @param database pointer to the 2D floats array to be deallocated.
 * @param arrayLength outer array length (number of rows).
 * @return none.
 */
void freeFloatMemory(float **database, int arrayLength) {
    //iterate through each string in the array and free its memory
    for(int i = 0; i < arrayLength; i++) {
        free(database[i]);
    }

    //free the memory allocated for the array itself
    free(database);
}

/**
 * this function deallocates memory that was dynamically allocated for all databases: `userDb`, `moviesDb`, and `ratingsDb`.
 * 
 * it checks if each database pointer is not NULL before attempting to free its memory.
 * @return none.
 */
void freeAllMemory() {
    //free memory for userDb
    if(userDb != NULL) {
        freeCharMemory(userDb, usersCount);
    }
    //free memory for moviesDb
    if(moviesDb != NULL) {
        freeCharMemory(moviesDb, moviesCount);
    }
    //free memory for ratingsDb
    if(ratingsDb != NULL) {
        freeFloatMemory(ratingsDb, usersCount);
    }
}